#!/usr/bin/env php
<?php
/*
 * @copyright  2018 Jack Clayton
 * @license    MIT
 */

use Jstewmc\Gravity\Gravity;
use Jstewmc\Gravity\Project\Service\Validate;

// require Composer's autoload or die
$pathnames = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
];

foreach ($pathnames as $pathname) {
    if (file_exists($pathname)) {
        break;
    }
}

if (isset($pathname)) {
    require_once $pathname;
} else {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

// execute command
$command = $argv[1];

if ($command === 'validate') {
    $g = (new Gravity())->pull();

    $errors = $g->get(Validate::class)($g->getProject(), $g);

    if (count($errors) === 0) {
        fwrite(STDOUT, "Project is valid!" . PHP_EOL);

        exit(0);
    } else {
        $total = count($errors);

        fwrite(
            STDERR,
            "Project is invalid! Found {$total} errors:" . PHP_EOL . PHP_EOL
        );

        foreach ($errors as $key => $error) {
            fwrite(STDERR, "    * {$key}: {$error}" . PHP_EOL . PHP_EOL);
        }

        exit(1);
    }
}
